//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissYangQA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MissYangQADBEntities : DbContext
    {
        public MissYangQADBEntities()
            : base("name=MissYangQADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Answer> T_Answer { get; set; }
        public virtual DbSet<T_ClassList> T_ClassList { get; set; }
        public virtual DbSet<T_Paper> T_Paper { get; set; }
        public virtual DbSet<T_Question> T_Question { get; set; }
        public virtual DbSet<T_Scantron> T_Scantron { get; set; }
        public virtual DbSet<T_ScantronDetailed> T_ScantronDetailed { get; set; }
        public virtual DbSet<T_Token> T_Token { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<V_User> V_User { get; set; }
    }
}
