//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissYangQA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Answer()
        {
            this.T_AnswerSheetDetails = new HashSet<T_AnswerSheetDetails>();
        }
    
        public System.Guid ID { get; set; }
        public string Contents { get; set; }
        public int Rank { get; set; }
        public bool IsRight { get; set; }
        public System.Guid FK_Problem { get; set; }
    
        public virtual T_Problem T_Problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AnswerSheetDetails> T_AnswerSheetDetails { get; set; }
    }
}
