//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissYangQA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Scantron
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Scantron()
        {
            this.T_ScantronDetailed = new HashSet<T_ScantronDetailed>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid FK_Paper { get; set; }
        public System.Guid FK_ClassList { get; set; }
        public int Score { get; set; }
        public string StudentName { get; set; }
    
        public virtual T_ClassList T_ClassList { get; set; }
        public virtual T_Paper T_Paper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ScantronDetailed> T_ScantronDetailed { get; set; }
    }
}
